export default {
    "light": {
        "Known word": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        },
        "New word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#ffD08B",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": false
        },
        "Level 1 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 86,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        },
        "Level 2 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 70,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        },
        "Level 3 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 60,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        },
        "Level 4 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 45,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        },
        "Level 5 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 30,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        },
        "Level 6 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 15,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        },
        "Level 7 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        },
        "Ignored word": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        },
        "Known phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        },
        "Level 1 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 86,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        },
        "Level 2 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 70,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        },
        "Level 3 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 60,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        },
        "Level 4 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 45,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        },
        "Level 5 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 30,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        },
        "Level 6 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 15,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        },
        "Level 7 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333"
        }
    },
    "dark": {
        "Known word": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "New word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#ffD08B",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": false
        },
        "Level 1 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 86,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 2 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 70,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 3 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 60,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 4 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 45,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 5 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 30,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 6 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 15,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 7 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Ignored word": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Known phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 1 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#47A54D",
            "backgroundTransparency": 86,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 2 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#47A54D",
            "backgroundTransparency": 70,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 3 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#47A54D",
            "backgroundTransparency": 60,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 4 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#47A54D",
            "backgroundTransparency": 45,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 5 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#47A54D",
            "backgroundTransparency": 30,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 6 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#47A54D",
            "backgroundTransparency": 15,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 7 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#47A54D",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        }
    },
    "eink": {
        "Known word": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "New word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#ffD08B",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": false
        },
        "Level 1 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 86,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 2 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 70,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 3 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 60,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 4 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 45,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 5 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 30,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 6 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 15,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 7 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Ignored word": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Known phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 1 phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 2 phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 3 phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 4 phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 5 phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 6 phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        },
        "Level 7 phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd"
        }
    }
}