export default {
    "light": {
        "Known word": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "New word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": false,
            "borderBottom": true,
            "borderSides": false,
            "borderColor": "#dddddd",
            "backgroundColor": "#ffD08B",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 1 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 60,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 2 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 50,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 3 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 40,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 4 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 30,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 5 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 20,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 6 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 10,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 7 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Ignored word": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Known phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 1,
            "paddingBottom": 1,
            "borderWidth": 1,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#929292",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 1 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 60,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 2 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 50,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 3 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 40,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 4 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 30,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 5 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 20,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 6 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 10,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 7 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#71EB7A",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        }
    },
    "dark": {
        "Known word": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "New word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#ffD08B",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#333333",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 1 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 60,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 2 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 50,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 3 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 40,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 4 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 30,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 5 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 20,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 6 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 10,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 7 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Ignored word": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Known phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 1,
            "paddingBottom": 1,
            "borderWidth": 1,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 1 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 60,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 2 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 50,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 3 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 40,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 4 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 30,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 5 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 20,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 6 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 10,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 7 phrase": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#dddddd",
            "backgroundColor": "#49A74F",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#dddddd",
            "horizontalPaddingSpacelessLanguagesOnly": true
        }
    },
    "eink": {
        "Known word": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#000000",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#000000",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "New word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 1,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": false,
            "borderBottom": true,
            "borderSides": false,
            "borderColor": "#000000",
            "backgroundColor": "#FFFFFF",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#000000",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 1 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#000000",
            "backgroundColor": "#000000",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#FFFFFF",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 2 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#000000",
            "backgroundColor": "#000000",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#FFFFFF",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 3 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#000000",
            "backgroundColor": "#000000",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#FFFFFF",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 4 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#000000",
            "backgroundColor": "#000000",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#FFFFFF",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 5 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#000000",
            "backgroundColor": "#000000",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#FFFFFF",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 6 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#000000",
            "backgroundColor": "#000000",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#FFFFFF",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 7 word": {
            "paddingHorizontal": 4,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#000000",
            "backgroundColor": "#000000",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#FFFFFF",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Ignored word": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 1,
            "borderRadius": 0,
            "borderStyle": "solid",
            "borderTop": false,
            "borderBottom": false,
            "borderSides": false,
            "borderColor": "#28272C",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#000000",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Known phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 1,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#000000",
            "backgroundColor": "#28272C",
            "backgroundTransparency": 100,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#000000",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 1 phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#000000",
            "backgroundColor": "#000000",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#FFFFFF",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 2 phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#000000",
            "backgroundColor": "#000000",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#FFFFFF",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 3 phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#000000",
            "backgroundColor": "#000000",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#FFFFFF",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 4 phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#000000",
            "backgroundColor": "#000000",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#FFFFFF",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 5 phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#000000",
            "backgroundColor": "#000000",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#FFFFFF",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 6 phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#000000",
            "backgroundColor": "#000000",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#FFFFFF",
            "horizontalPaddingSpacelessLanguagesOnly": true
        },
        "Level 7 phrase": {
            "paddingHorizontal": 0,
            "paddingHorizontalSpacelessLanguages": 0,
            "paddingTop": 2,
            "paddingBottom": 2,
            "borderWidth": 0,
            "borderRadius": 5,
            "borderStyle": "solid",
            "borderTop": true,
            "borderBottom": true,
            "borderSides": true,
            "borderColor": "#000000",
            "backgroundColor": "#000000",
            "backgroundTransparency": 0,
            "bold": false,
            "italic": false,
            "wavyUnderline": false,
            "textColor": "#FFFFFF",
            "horizontalPaddingSpacelessLanguagesOnly": true
        }
    }
}