<?php

return [

    'languages' => [
        // A list of the supported languages that can be read with linguacafe. 
        'supported_languages' => [
            'Chinese',
            'Czech',
            'Dutch',
            'Finnish',
            'French',
            'German',
            'Italian',
            'Japanese',
            'Norwegian',
            'Korean',
            'Russian',
            'Spanish',
            'Swedish',
            'Ukrainian',
            'Welsh',
        ],

        /*
            List of languages that can be selected for target language. These should also have flag images.
        */
        'supported_target_languages' => [
            'Chinese',
            'Arabic',
            'Brazilian portuguese',
            'Bulgarian',
            'Chinese',
            'Czech',
            'Czech',
            'Danish',
            'Dutch',
            'English',
            'Estonian',
            'Finnish',
            'French',
            'German',
            'Greek',
            'Hungarian',
            'Indonesian',
            'Italian',
            'Japanese',
            'Korean',
            'Latvian',
            'Lithuanian',
            'Norwegian',
            'Polish',
            'Portuguese',
            'Romanian',
            'Russian',
            'Slovak',
            'Slovenian',
            'Spanish',
            'Swedish',
            'Turkish',
            'Ukrainian',
            'Welsh',
        ],

        /*
            List of target languages that are supported by DeepL.
        */
        'deepl_supported_target_languages' => [
            'Arabic',
            'Brazilian portuguese',
            'Bulgarian',
            'Chinese',
            'Czech',
            'Danish',
            'Dutch',
            'English',
            'Estonian',
            'Finnish',
            'French',
            'German',
            'Greek',
            'Hungarian',
            'Indonesian',
            'Italian',
            'Japanese',
            'Korean',
            'Latvian',
            'Lithuanian',
            'Norwegian',
            'Polish',
            'Portuguese',
            'Romanian',
            'Russian',
            'Slovak',
            'Slovenian',
            'Spanish',
            'Swedish',
            'Turkish',
            'Ukrainian',
        ],

        /*
            A list of supported languages by Newspaper3k python library. This library 
            is used for importing websites, and also RSS feed.
        */
        'website_import_supported_languages' => [
            'Arabic',
            'Belarusian',
            'Bulgarian',
            'Danish',
            'German',
            'Greek',
            'English',
            'Spanish',
            'Estonian',
            'Persian',
            'Finnish',
            'French',
            'Hebrew',
            'Hindi',
            'Croatian',
            'Hungarian',
            'Indonesian',
            'Italian',
            'Japanese',
            'Korean',
            'Lithuanian',
            'Macedonian',
            'Norwegian',
            'Dutch',
            'Norwegian',
            'Polish',
            'Portuguese',
            'Romanian',
            'Russian',
            'Slovenian',
            'Serbian',
            'Swedish',
            'Swahili',
            'Thai',
            'Turkish',
            'Ukrainian',
            'Vietnamese',
            'Chinese',


            'arabic',
            'belarusian',
            'bulgarian',
            'danish',
            'german',
            'greek',
            'english',
            'spanish',
            'estonian',
            'persian',
            'finnish',
            'french',
            'hebrew',
            'hindi',
            'croatian',
            'hungarian',
            'indonesian',
            'italian',
            'japanese',
            'korean',
            'lithuanian',
            'macedonian',
            'norwegian',
            'dutch',
            'norwegian',
            'polish',
            'portuguese',
            'romanian',
            'russian',
            'slovenian',
            'serbian',
            'swedish',
            'swahili',
            'thai',
            'turkish',
            'ukrainian',
            'vietnamese',
            'chinese',
        ],

        /*
            These are language codes that Jellyfin uses for subtitles. You can find out what
            a jellyfin language code is by going to the media player, and starting a video
            with a new language subtitle. If that new language is not added here, you will see
            a javascript log about the unsupported languages code.
        */
        'jellyfin_language_codes' => [
            'jpn' => 'japanese',
            'eng' => 'english',
            'nor' => 'norwegian',
            'ger' => 'german',
            'spa' => 'spanish',
            'chi' => 'chinese',
            'dut' => 'dutch',
            'fin' => 'finnish',
            'fre' => 'french',
            'ita' => 'italian',
            'kor' => 'korean',
            'swe' => 'swedish',
            'ukr' => 'ukrainian',
            'rus' => 'russian',
            'wel' => 'welsh',
            'cze' => 'czech',
        ],

        /*
            These language codes are used to create 
            database tables for dictionaries.
        */
        'database_name_language_codes' => [
            'japanese' => 'jp',
            'norwegian' => 'no',
            'german' => 'de',
            'spanish' => 'es',
            'chinese' => 'zh',
            'dutch' => 'nl',
            'finnish' => 'fi',
            'french' => 'fr',
            'italian' => 'it',
            'korean' => 'ko',
            'swedish' => 'sv',
            'ukrainian' => 'ua',
            'russian' => 'ru',
            'welsh' => 'cy',
            'czech' => 'cs',

            'Japanese' => 'jp',
            'Norwegian' => 'no',
            'German' => 'de',
            'Spanish' => 'es',
            'Chinese' => 'zh',
            'Dutch' => 'nl',
            'Finnish' => 'fi',
            'French' => 'fr',
            'Italian' => 'it',
            'Korean' => 'ko',
            'Swedish' => 'sv',
            'Ukrainian' => 'ua',
            'Russian' => 'ru',
            'Welsh' => 'cy',
            'Czech' => 'cs',
        ],

        /*
            These are needed to recognize dict cc dictionary
            files inside the dictionaries directory. These 
            language codes can be found in the first line of 
            dict cc dictionary files.
        */
        'dict_cc_language_codes' => [
            'NO' => 'norwegian',
            'CS' => 'czech',
            'DE' => 'german',
            'NL' => 'dutch',
            'ES' => 'spanish',
            'FI' => 'finnish',
            'FR' => 'french',
            'IT' => 'italian',
            'SV' => 'swedish',
            'RU' => 'russian',
        ],

        // ISO_639-1 codes, with a few exceptions (en-GB)
        'deepl_language_codes' => [
            'japanese' => 'JA',
            'norwegian' => 'NB',
            'german' => 'DE',
            'english' => 'EN-US',
            'chinese' => 'ZH',
            'dutch' => 'NL',
            'finnish' => 'FI',
            'french' => 'FR',
            'italian' => 'IT',
            'korean' => 'KO',
            'spanish' => 'ES',
            'swedish' => 'SV',
            'ukrainian' => 'UK',
            'russian' => 'RU',
            'czech' => 'CS',
            'arabic' => 'AR',
            'bulgarian' => 'BG',
            'danish' => 'DA',
            'greek' => 'EL',
            'estonian' => 'ET',
            'hungarian' => 'HU',
            'indonesian' => 'ID',
            'lithuanian' => 'LT',
            'latvian' => 'LV',
            'polish' => 'PL',
            'portuguese' => 'PT-PT',
            'brazilian Portuguese' => 'PT-BR',
            'romanian' => 'RO',
            'slovak' => 'SK',
            'slovenian' => 'SL',
            'turkish' => 'TR',

            'Japanese' => 'JA',
            'Norwegian' => 'NB',
            'German' => 'DE',
            'English' => 'EN-US',
            'Chinese' => 'ZH',
            'Dutch' => 'NL',
            'Finnish' => 'FI',
            'French' => 'FR',
            'Italian' => 'IT',
            'Korean' => 'KO',
            'Spanish' => 'ES',
            'Swedish' => 'SV',
            'Ukrainian' => 'UK',
            'Russian' => 'RU',
            'Czech' => 'CS',
            'Arabic' => 'AR',
            'Bulgarian' => 'BG',
            'Danish' => 'DA',
            'Greek' => 'EL',
            'Estonian' => 'ET',
            'Hungarian' => 'HU',
            'Indonesian' => 'ID',
            'Lithuanian' => 'LT',
            'Latvian' => 'LV',
            'Polish' => 'PL',
            'Portuguese' => 'PT-PT',
            'Brazilian Portuguese' => 'PT-BR',
            'Romanian' => 'RO',
            'Slovak' => 'SK',
            'Slovenian' => 'SL',
            'Turkish' => 'TR',
        ],
    ],
    'words_to_skip' => ['。', '、', ':', '？', '！', '＜', '＞', '：', ' ', '「', '」', '（', '）', '｛', '｝', '≪', '≫', '〈', '〉',
        '《', '》','【', '】', '『', '』', '〔', '〕', '［', '］', '・', '?', '(', ')', ' ', ' NEWLINE ', '.', '%', '-',
        '«', '»', "'", '’', '–', 'NEWLINE', 'newline', ' ', "\r", "\n", "\r\n", '	', "\r\n　", ';', ',', '!', '\'', 
        '"', '‘', '_', '…', '/', '*', '&', '“', '”', '•', '©', '...', '●', '¡', '¿', '€', '$', '%', '˚', '°', '=', '!=', '-', '+'],

    'tokens_with_no_space_before' => ['.', ',', '?', '!', '\'', '"', '‘', '’'],
    'tokens_with_no_space_after' => ['‘', '’'],
];
